Add step by step instructions on contributing using git
msdemlei/ivoatexDoc pull request #2
Opened 2021-11-15 10:11 UTC by jd-au

2021-11-15 10:24 UTC, molinaro-m commented on ivoatexDoc.tex
> +git commit
Should we suggest a
`git commit -m "a useful short description of my changes`
as well as a reminder on the `git add whta files you changed` ?

Or would that be too much basic detail?

2021-11-15 10:26 UTC, molinaro-m approved these changes
I like the text as well as the triangle diagram.
I added a small comment that is not critical to the approval , IMHO.

2021-11-15 12:02 UTC, msdemlei requested changes
In general, I'd ask everyone to author with ~72 characters per line (and not reflowing for general commits) -- it makes later diffs much easier to comprehend.  You know, it's source code...

Other than that, would you add triangle_workflow.png to FIGURES in the makefile?

2021-11-15 20:54 UTC, jd-au commented on ivoatexDoc.tex
> +git commit
I think we should, particularly as I forgot to include the Makefile in my first commit! I've made those changes.

2021-11-15 20:55 UTC, jd-au commented
> In general, I'd ask everyone to author with ~72 characters per line (and not reflowing for general commits) -- it makes later diffs much easier to comprehend. You know, it's source code...
> 
> Other than that, would you add triangle_workflow.png to FIGURES in the makefile?

2021-11-17 09:51 UTC, msdemlei approved these changes

2021-11-17 09:53 UTC, merged